baseURL = 'https://pbc86.github.io/cloudcannon'
languageCode = 'en-us'
title = 'Cau Hugo Site'

[params]
name = 'Simba'


[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup.goldmark.renderHooks.image]
enableDefault = true

[markup.goldmark.renderHooks.link]
enableDefault = true